vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        meals:
            uri_prefix: /uploaded/mealsimg
            upload_destination: '%kernel.project_dir%/public/uploaded/mealsimg'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
