CREATE TABLE booking (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  day VARCHAR(255) NOT NULL,
  hours INT NOT NULL,
  guests INT NOT NULL,
  allergies VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)

CREATE TABLE posts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  content TEXT(65000) NOT NULL,
  PRIMARY KEY (id)
)

CREATE TABLE menus (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  content TEXT(65000) NOT NULL,
  price INT NOT NULL,
  PRIMARY KEY (id)
)

CREATE TABLE meals (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  content TEXT(65000) NOT NULL,
  price INT NOT NULL,
  category VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)

CREATE TABLE opening (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  days VARCHAR(255) NOT NULL,
  openlunch INT NOT NULL,
  closelunch INT NOT NULL,
  opendinner INT NOT NULL,
  closedinner INT NOT NULL,
  PRIMARY KEY (id)
)
